export const QUOTES = [
  "Дисципліна — це вибір між тим, чого ти хочеш зараз, і тим, чого ти хочеш найбільше.",
  "Ти не відчуваєш мотивації, щоб почати. Ти відчуваєш мотивацію після того, як почав.",
  "Кожен день — це новий шанс стати кращою версією себе.",
  "Важко — означає, що воно того варте.",
  "Той, хто не знайде часу на здоров'я, буде змушений знайти час на хворобу.",
  "Не порівнюй себе з іншими. Порівнюй себе з тим, ким ти був учора.",
  "Успіх — це сума маленьких зусиль, які повторюються день за днем.",
  "Ніхто не запам'ятає твої відмовки. Всі запам'ятають твої результати.",
  "Зміни відбуваються не в зоні комфорту.",
  "Твоє тіло може витримати майже все. Треба переконати розум.",
  "Один рік наполегливої роботи може змінити все.",
  "Не чекай натхнення. Починай, і натхнення прийде.",
  "Найкращий час посадити дерево був 20 років тому. Другий найкращий — зараз.",
  "Середній результат — наслідок середніх зусиль.",
  "Прокидайся з рішучістю, лягай із задоволенням.",
  "Твої звички визначають твоє майбутнє.",
  "Страждай зараз і живи як чемпіон.",
  "Кожне тренування важливе. Кожен пропуск теж.",
  "Сила волі — це м'яз. Тренуй його щодня.",
  "6 місяців. 180 днів. Твій вибір.",
  "We are what we repeatedly do. Excellence is not an act, but a habit.",
  "The man who moves a mountain begins by carrying away small stones.",
  "Don't count the days. Make the days count.",
  "It's not about having time. It's about making time.",
  "The pain you feel today will be the strength you feel tomorrow.",
  "Hard work beats talent when talent doesn't work hard.",
  "You don't rise to the level of your goals, you fall to the level of your systems.",
  "Suffer the pain of discipline or suffer the pain of regret.",
  "Champions aren't made in the gyms. Champions are made from something deep inside.",
  "The only bad workout is the one that didn't happen.",
  "Small daily improvements over time lead to stunning results.",
  "Your future self is watching you right now through memories.",
  "Fall in love with the process and the results will come.",
  "Be so good they can't ignore you.",
  "The secret of getting ahead is getting started.",
  "Do something today that your future self will thank you for.",
  "Energy and persistence conquer all things.",
  "The body achieves what the mind believes.",
  "Push yourself because no one else is going to do it for you.",
  "Wake up with determination. Go to bed with satisfaction.",
  "You are one decision away from a completely different life.",
  "Discipline is doing what needs to be done even when you don't want to do it.",
  "The harder you work for something, the greater you'll feel when you achieve it.",
  "Dream big. Start small. Act now.",
  "Your only limit is your mind.",
  "Success is not final, failure is not fatal — it's the courage to continue.",
  "Believe you can and you're halfway there.",
  "One day or day one. You decide.",
  "Make yourself proud.",
  "6 months. No excuses.",
];

export function getQuoteOfDay(): string {
  const start = new Date(new Date().getFullYear(), 0, 0);
  const dayOfYear = Math.floor((Date.now() - start.getTime()) / 86400000);
  return QUOTES[dayOfYear % QUOTES.length];
}
